name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 6.0.x 
    - name: Check out Code
      uses: actions/checkout@v3
      with:
         fetch-depth: 0
    - name: Build Cake
      run: |
        chmod +x build.sh
        ./build.ps1 --target Test